# Generated by Django 4.1.7 on 2023-03-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_alter_startupdetails_investment_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartupDetails',
            new_name='StartupDetail',
        ),
        migrations.RenameModel(
            old_name='StartupTags',
            new_name='StartupTag',
        ),
    ]
